name "dokku"
maintainer "Nick Charlton"
maintainer_email "nick@nickcharlton.net"
license "mit"
description "Manages a dokku install."
long_description "Manages a dokku install and provides LWRPs for managing apps."
version "3.0.0"

depends "apt", "~> 6.1.4"
depends "docker", "4.1.1"
depends "packagecloud", "~> 1.0.0"
depends "openssl", "~> 8.1.2"

recipe "default", "Triggers install cookbooks and provides the LWRP."
recipe "install", "Installs and configures dokku dependencies"
recipe "plugins", "Installs and configures plugins"
recipe "ssh_keys", "Installs and configures ssh_keys"
recipe "certificates", "Configures certificates for dokku apps"
